### PR TITLE
Update README: Correct Usage of --source and --target Flags in Analyze Command

### PR DESCRIPTION
**Pull request by midays**

### CODE REVIEW

**Review by pranavgaikwad — APPROVED** [review]
@midays Thank you for taking the time to fix this!

**Review by aufi — APPROVED** [review]

**Review by abrugaro — APPROVED** [review]

**Comment by eemcmullan** [comment]
@midays thank you for the PR! A couple of comments: Can we keep the types listed in the README as stringArray? They are defined as such here https://github.com/konveyor/kantra/blob/main/cmd/analyze.go#L56-L57. Also, can we add the same description to the commands themselves? That way `--help` will display that info. Lastly, because these two commands work the same as `--rules`, can that be included too?

**Review by eemcmullan — CHANGES_REQUESTED** [review]
See comment

**Review by eemcmullan — APPROVED** [review]

**Comment by midays** [comment]
@eemcmullan Hi, I don't have write access so I cannot merge this branch

**Pull request merged**
